spring:
  application:
    name: spring-board
  config:
    import: ./config.yml
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
    #메일보낼 때 처음부터 암호화 처리를 해서 보내는게 아니라 정말로 메일이 가고 있을 때 암호화 처리를 진행
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    path: ${db.upload.profile-path}
    board-path: ${db.upload.board-path}

jwt:
  secret: ${jwt.config.secret}
  access-expiry: 1800000
  refresh-expiry: 1209600000